function vorticity=calc_newVorticity(stream,w,dx,dt,vL_Re,dx2)
% 2nd order CDS, 1st order FDTS
vorticity = ( ...
    -((stream(2:end-1,3:end) - stream(2:end-1,1:end-2)) / (2*dx)) .* ...
      ((w(3:end,2:end-1) - w(1:end-2,2:end-1)) / (2*dx)) ...
    +((stream(3:end,2:end-1) - stream(1:end-2,2:end-1)) / (2*dx)) .* ...
      ((w(2:end-1,3:end) - w(2:end-1,1:end-2)) / (2*dx)) ...
    + vL_Re * ( ...
        w(3:end,2:end-1) + w(1:end-2,2:end-1) + ...
        w(2:end-1,3:end) + w(2:end-1,1:end-2) - ...
        4*w(2:end-1,2:end-1) ) / dx2 ...
    ) * dt + w(2:end-1,2:end-1);
return